name: Build

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/check.yml
  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: LocalPublish
        run: ./gradlew -i publish